# Site settings
title: Design Automation
email: me@jeffreylarrimore.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
